### PR TITLE
logn example

### LINKED ISSUE #9: [Documentation] implement a logarithmic time complexity funcion
in Module 1 - Big O Notation

### PR DESCRIPTION
**Pull request by DanielXing1103**
resolves #9 by adding Binary Search

### CODE REVIEW

**Comment by eduardonard** [comment]
Thank you very much for contributing! This means a lot!

**Review by eduardonard — CHANGES_REQUESTED** [review]
Delete empty lines and multi line comments

**Comment by DanielXing1103** [comment]
Yes of course.

**Comment by eduardonard** [comment]
Perfect! Thank You!

**Pull request merged**
